# Generated by Django 3.0.5 on 2020-06-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0003_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='orderitems',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='phoneno',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='username',
            field=models.CharField(max_length=120),
        ),
    ]
