# Generated by Django 3.0.5 on 2020-06-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0005_auto_20200615_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='ordereditems',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
